apiVersion: v1
kind: Service
metadata:
  name: back-service-sv
  labels:
    app: back-service-sv
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8000
    targetPort: 8000
    nodePort: 30010
  
  selector:
    app: back-service