version: '3.1'
services:
# Postgresql
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - 5432:5432
#     volumes:
#       - ./volumes/Postgres/init:/docker-entrypoint-initdb.d
#       - ./volumes/Postgres/data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: gihub_uks
# # Adminer 
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# # Django application
#   backEnd:
#     container_name: myapp_web_backend
#     labels:
#       com.example.service: "web"
#       com.example.description: "Use for the main web process"
#     image: myapp_web_backend:latest
#     command: ["./wait_for_postgres.sh"]
#     ports:
#       - 8000:8000
#     logging:
#       driver: "json-file"
#     depends_on:
#       - db
#     environment:
#       - POSTGRES_PASSWORD=gihub_uks
#       - POSTGRES_USER=gihub_uks
#       - POSTGRES_DB=gihub_uks

# Angular app
  frontEnd:
    container_name: myapp_web_frontebd
    image: myapp_web_frontend:latest
    # depends_on:
    #   - backEnd
    ports:
      - 4200:4200

  