apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
spec:
  selector:
    matchLabels:
      app: front-service
  replicas: 1
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
      - name: front-service
        image: dusanbucan/myapp_web_frontend:latest
        # imagePullPolicy: always
        ports:
        - containerPort: 4200