# Generated by Django 3.1.6 on 2021-02-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_milestone_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
