# Generated by Django 3.1.6 on 2021-02-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0003_auto_20210216_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='labels',
        ),
    ]
