# Generated by Django 3.1.6 on 2021-02-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0004_remove_milestone_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='tasks',
        ),
    ]
