# Generated by Django 3.1.5 on 2021-01-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_user', '0001_initial'),
        ('project', '0001_initial'),
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_user.githubuser', verbose_name='user'),
        ),
    ]
