# Generated by Django 3.1.6 on 2021-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_auto_20210127_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='commit',
            name='hash',
            field=models.CharField(max_length=1000, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='commit',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='summary')
        ),
    ]
