# Generated by Django 3.1.5 on 2021-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0002_auto_20210128_1533'),
        ('label', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(null=True, to='label.Label'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(null=True, to='github_user.GitHubUser', verbose_name='users'),
        ),
    ]
