# Generated by Django 3.1.6 on 2021-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0002_auto_20210128_1533'),
        ('label', '0001_initial'),
        ('project', '0003_project_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(to='label.Label'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='github_user.GitHubUser', verbose_name='users'),
        ),
    ]
