# Generated by Django 3.1.5 on 2021-01-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_users', models.ManyToManyField(to='github_user.GitHubUser')),
            ],
        ),
    ]
