# Generated by Django 3.1.6 on 2021-02-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_auto_20210217_1459'),
        ('github_user', '0002_auto_20210128_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('git_users', models.ManyToManyField(to='github_user.GitHubUser')),
                ('projects', models.ManyToManyField(to='project.Project')),
            ],
        ),
    ]
