# Generated by Django 3.1.6 on 2021-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=-1, max_length=500, verbose_name='name'),
            preserve_default=False,
        ),
    ]
