# Generated by Django 3.1.5 on 2021-01-27 23:08

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('username', models.CharField(max_length=500, verbose_name='username')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('last_name', models.CharField(max_length=500, verbose_name='last name')),
                ('email', models.EmailField(max_length=500, verbose_name='email')),
                ('photo', models.CharField(max_length=500, verbose_name='photo')),
                ('gitlab_profile_url', models.CharField(max_length=500, verbose_name='gitlab profile url')),
                ('organization', models.TextField(max_length=500, verbose_name='organisation')),
                ('member_since', models.DateTimeField(default=django.utils.timezone.now, verbose_name='member since')),
                ('skype', models.TextField(max_length=500, verbose_name='skype')),
                ('twitter', models.TextField(max_length=500, verbose_name='twitter')),
                ('linkedin', models.TextField(max_length=500, verbose_name='linkedin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='github_user.userproxy')),
            ],
            options={
                'verbose_name': 'GitHub user',
                'verbose_name_plural': 'GitHub users',
            },
        ),
    ]
