# Generated by Django 3.1.5 on 2021-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='gitlab_profile_url',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='username',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='github_profile_url',
            field=models.CharField(default=-1, max_length=500, verbose_name='github profile url'),
            preserve_default=False,
        ),
    ]
