# Generated by Django 3.1.6 on 2021-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210216_1502'),
        ('task', '0002_auto_20210216_1511'),
    ]

    operations = [
    ]
