# Generated by Django 3.1.6 on 2021-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0005_remove_milestone_tasks'),
        ('task', '0002_auto_20210216_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestones',
            field=models.ManyToManyField(to='milestone.Milestone'),
        ),
    ]
