# Generated by Django 3.1.5 on 2021-02-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0002_auto_20210128_1533'),
        ('task', '0003_task_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='github_user.githubuser', verbose_name='assignee'),
        ),
    ]
